baseurl = "https://mrpopov.com"
languageCode = "en-us"
theme = "hello-friend"
publishDir = "docs"
relativeurls = true
rssFullText = true
rssImage = "image/url/here"
canonifyurls = true
enableRobotsTXT = false

[pagination]
pagerSize = 5

staticDir = ['static']

PygmentsCodeFences = true
PygmentsStyle = "github"

[markup]
[markup.highlight]
style = 'github'
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
contentTypeName = "posts"
defaultTheme = "light"
showMenuItems = 2
showReadingTime = true
summary_length = 50
twitter = "lalabuy948"

[params.feed]
copyright = "Copyright 203"
itunes_subtitle = "The best podcast ever"
itunes_author = "Daniil Popov"
itunes_summary = "Some awesome description"
itunes_owner_name = "Daniil Popov"
itunes_owner_email = "lalabuy9948@gmail.com"
itunes_image = "https://mrpopov.com/img/mrpopov1.webp"
itunes_top_category = "Technology"
itunes_first_sub_category = "Software How-To"
itunes_second_sub_category = "Tech News"
language = "en-us"
explicit = false

[languages]
[languages.en]
[languages.en.params]
title = "MrPopov"
description = "Daniil Popov - Result oriented fractional CTO with proven track record. Over decade of experience in technology, product building, people management and processes establishment. Based in Luxembourg, operate remotely."
keywords = "daniil popov, mrpopov, popov com, daniil, mr popov, senior, procrastinator, fractional CTO, CTO as a Service"
copyright = "Daniil Popov"
menuMore = "More üëá"
writtenBy = "Written by"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Here"
olderPosts = "There"
minuteReadingTime = "‚òïÔ∏è"
dateFormatSingle = "02-01-2006"
dateFormatList = "02-01-2006"

[languages.en.params.logo]
logoText = "Mr. Popov"
logoHomeLink = "/"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "1703"
name = "1703"
url = "https://1703.lu"
[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"
[[languages.en.menu.main]]
identifier = "cv"
name = "CV"
url = "/cv/"
[[languages.en.menu.main]]
identifier = "dribbble"
name = "Me on dribbble"
url = "https://dribbble.com/lalabuy"
[[languages.en.menu.main]]
identifier = "behance"
name = "Me on behance"
url = "https://www.behance.net/lalabuy"
[[languages.en.menu.main]]
identifier = "linkedin"
name = "Me on linkedin"
url = "https://www.linkedin.com/in/mrpopov/"
[[languages.en.menu.main]]
identifier = "github"
name = "Me on github"
url = "https://github.com/lalabuy948"
[[languages.en.menu.main]]
identifier = "pexels"
name = "Me on pexels"
url = "https://www.pexels.com/@daniil-popov-1864765"
[[languages.en.menu.main]]
identifier = "discord"
name = "Join discord"
url = "https://discord.gg/nrpaSurVWV"
[[languages.en.menu.main]]
identifier = "zprojects"
name = "Pets graveyard"
url = "/projects"
